base_kwargs:
  name: Test
  save_dir: /mnt/scratch/Saved_Networks/METNet/
  device: gpu
reg_loss_fn: huber
dst_loss_fn: energymmd
dst_weight: 10
dense_kwargs:
  act_h: silu
  num_blocks: 3
  hddn_dim: 128
  nrm: layer